[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tract-onnx = "0.15.8"
dioxus = {version = "0.2.3", features = ["desktop"]}
serde_json = "1.0.79"
league-client-connector = "0.1.2"
tokio = { version = "1.13.0", features = ["full"] }
reqwest = { version = "0.11.9", features = ["json"] }
lazy_static = "1.4.0"